web/blueprints/donor.py
from flask import Blueprint, render_template, redirect, flash, url_for

from models import RecipientChannel, DonorChannel

from web.utils import login_required


bp = Blueprint("donor", __name__)


@bp.route("/donor/<int:id>", methods=["GET"])
@login_required
async def donor_page(id: int):
    donor = await DonorChannel.get_or_none(id=id)
    if not donor:
        flash("Канал не найден", "error")
        return redirect(url_for("index"))

    await donor.fetch_related("recipient_channel")
    return render_template("donor.html", donor=donor)


@bp.route("/donor/<int:id>", methods=["DELETE"])
@bp.route("/donor/delete/<int:id>", methods=["POST"])
@login_required
async def delete_donor(id: int):
    donor = await DonorChannel.get_or_none(id=id)
    if not donor:
        flash("Канал-донор не найден", "error")
        return redirect(url_for("index"))

    recipient: RecipientChannel = await donor.recipient_channel
    if len(await recipient.donor_channels) == 1:
        flash(
            "Канал-донор не может быть удален, так как он единственный. Для удаления сначала добавьте другой канал-донор или удалите канал-получатель целиком",
            "error",
        )
        return redirect(url_for("donor.donor_page", id=id))

    await donor.delete()

    flash("Канал-донор успешно удален", "success")
    return redirect(url_for("index"))


@bp.route("/donor/<int:id>/toggle", methods=["POST"])
@login_required
async def toggle_donor(id: int):
    donor = await DonorChannel.get_or_none(id=id)
    if not donor:
        flash("Канал не найден", "error")
        return redirect(url_for("index"))

    donor.is_active = not donor.is_active
    await donor.save()

    flash(
        "Пересылка востановлена" if donor.is_active else "Пересылка отключена",
        "success" if donor.is_active else "warning",
    )

    return redirect(url_for("index"))

web/blueprints/filter.py
from flask import Blueprint, render_template, redirect, request, flash, url_for

from models import Filter, RecipientChannel, DonorChannel, FilterScope, FilterAction

from web.utils import login_required


bp = Blueprint("filter", __name__)


@bp.route("/filter/<int:id>", methods=["GET"])
@login_required
async def filter_page(id: int):
    filter = await Filter.get_or_none(id=id)
    if not filter:
        flash("Фильтр не найден", "error")
        return redirect(url_for("index"))

    return render_template("filter.html", filter=filter)


@bp.route("/filter/<int:id>", methods=["DELETE"])
@bp.route("/filter/delete/<int:id>", methods=["POST"])
@login_required
async def delete_filter(id: int):
    filter = await Filter.get_or_none(id=id)
    if not filter:
        flash("Фильтр не найден", "error")
        return redirect(url_for("index"))

    await filter.delete()
    flash("Фильтр успешно удален", "success")
    return redirect(url_for("index"))


@bp.route("/filter/add/", methods=["GET"])
@login_required
async def add_filter_page():
    recipients = await RecipientChannel.all()
    donors = await DonorChannel.all().prefetch_related("recipient_channel")

    return render_template("add_filter.html", recipients=recipients, donors=donors)


@bp.route("/filter/add/", methods=["POST"])
@login_required
async def add_filter():
    try:
        scope = FilterScope(request.form.get("scope"))
        action = FilterAction(request.form.get("action"))
        pattern = request.form["pattern"]
        replace_with = request.form.get("replace_with")
        name = request.form["name"]
        is_case_sensitive = is_regex = False
        if request.form.get("is_case_sensitive") and request.form.get("is_case_sensitive")  == 'on':
            is_case_sensitive = True
        if request.form.get("is_regex") and request.form.get("is_regex") == 'on':
            is_regex = True

    except (ValueError, TypeError):
        flash("Данные некорректны или заполнены не все поля", "error")
        return redirect(url_for("index"))

    if scope == FilterScope.RECIPIENT:
        recipient_id = request.form.get("recipient_id")
        recipient = await RecipientChannel.get_or_none(id=recipient_id)
        if not recipient:
            flash("Канал-получатель не найден", "error")
            return redirect(url_for("index"))

        filter = await Filter.create(
            name=name,
            scope=scope,
            action=action,
            pattern=pattern,
            replace_with=replace_with,
            is_regex=is_regex,
            is_case_sensitive=is_case_sensitive,
            recipient_channel=recipient,
        )

        flash("Фильтр успешно добавлен", "success")
        return redirect(url_for("recipient.recipient_page", id=recipient_id))

    elif scope == FilterScope.DONOR:
        donor_id = request.form.get("donor_id")
        donor = await DonorChannel.get_or_none(id=donor_id)
        if not donor:
            flash("Канал-донор не найден", "error")
            return redirect(url_for("index"))

        filter = await Filter.create(
            name=name,
            scope=scope,
            action=action,
            pattern=pattern,
            replace_with=replace_with,
            is_regex=is_regex,
            is_case_sensitive=is_case_sensitive,
            donor_channel=donor,
        )

        flash("Фильтр успешно добавлен", "success")
        return redirect(url_for("donor.donor_page", id=donor_id))

    filter = await Filter.create(
        name=name,
        scope=scope,
        action=action,
        pattern=pattern,
        replace_with=replace_with,
        is_regex=is_regex,
        is_case_sensitive=is_case_sensitive,
    )

    flash("Фильтр успешно добавлен", "success")
    return redirect(url_for("index"))


@bp.route("/filter/<int:id>/toggle", methods=["POST"])
@login_required
async def toggle_filter(id: int):
    filter = await Filter.get_or_none(id=id)
    if not filter:
        flash("Фильтр не найден", "error")
        return redirect(url_for("index"))

    filter.is_active = not filter.is_active
    await filter.save()

    flash(
        "Фильтр востановлен" if filter.is_active else "Фильтр отключен",
        "success" if filter.is_active else "warning",
    )

    return redirect(url_for("index"))

web/blueprints/recipient.py
from flask import Blueprint, render_template, redirect, request, flash, url_for

from models import RecipientChannel, DonorChannel

from web.utils import login_required
from userbot.utils.utils import get_admined_and_possible_donor_channels, fill_channel

from userbot.start import client

bp = Blueprint("recipient", __name__)


@bp.route("/add_recipient", methods=["GET"])
@login_required
async def add_recipient_page():
    admined_channels, possible_donor_channels = await get_admined_and_possible_donor_channels(client)

    return render_template(
        "add_recipient.html",
        admined_channels=admined_channels,
        possible_donor_channels=possible_donor_channels,
    )


@bp.route("/add_recipient", methods=["POST"])
@login_required
async def add_recipient():
    if not (request.form.get("donor") and request.form.get("recipient")):
        flash("Заполните все обязательные поля", "error")
        return redirect(url_for("recipient.add_recipient_page"))

    if request.form.get("max_per_day") and request.form.get("max_per_day").isdigit():
        max_per_day = int(request.form.get("max_per_day"))
    else:
        max_per_day = 0
    donor_id = request.form.get("donor")
    recipient_id = request.form.get("recipient")
    if request.form.get("name"):
        name = request.form.get("name")
    else:
        name = (await client.get_chat(recipient_id)).title

    if donor_id == recipient_id:
        flash("Канал не может быть донором и получателем одновременно", "error")
        return redirect(url_for("recipient.add_recipient_page"))

    if await RecipientChannel.exists(channel_id=recipient_id):
        flash("Канал-получатель уже есть в базе", "error")
        return redirect(url_for("recipient.add_recipient_page"))

    donor_name = (await client.get_chat(donor_id)).title

    recipient_channel = await RecipientChannel.create(
        channel_id=recipient_id, name=name, max_forwarding_per_day=max_per_day
    )
    donor_channel = await DonorChannel.create(channel_id=donor_id, name=donor_name, recipient_channel=recipient_channel)

    flash("Канал-получатель успешно добавлен", "success")
    return redirect(url_for("index"))


@bp.route("/recipient/<int:id>", methods=["GET"])
@login_required
async def recipient_page(id: int):
    recipient = await RecipientChannel.get_or_none(id=id)
    if not recipient:
        flash("Канал не найден", "error")
        return redirect(url_for("index"))

    await recipient.fetch_related("donor_channels")
    return render_template("recipient.html", recipient=recipient)


@bp.route("/recipient/<int:id>", methods=["DELETE"])
@bp.route("/recipient/delete/<int:id>", methods=["POST"])
@login_required
async def delete_recipient(id: int):
    recipient = await RecipientChannel.get_or_none(id=id)
    if not recipient:
        flash("Канал не найден", "error")
        return redirect(url_for("index"))

    await recipient.delete()
    flash("Канал-получатель успешно удален", "success")
    return redirect(url_for("index"))


@bp.route("/recipient/<int:id>/add_donor", methods=["GET", "POST"])
@login_required
async def recipient_add_donor(id: int):
    recipient = await RecipientChannel.get_or_none(id=id)
    if not recipient:
        flash("Канал не найден", "error")
        return redirect(url_for("index"))

    if request.method == "GET":
        _, possible_donor_channels = await get_admined_and_possible_donor_channels(client)

        return render_template(
            "add_donor.html",
            recipient=recipient,
            possible_donor_channels=possible_donor_channels,
        )

    if not request.form.get("donor"):
        flash("Заполните все обязательные поля", "error")
        return redirect(url_for("recipient.recipient_add_donor", id=id))

    donor_id = request.form.get("donor")

    if donor_id == recipient.channel_id:
        flash("Канал не может быть донором и получателем одновременно", "error")
        return redirect(url_for("recipient.recipient_add_donor", id=id))

    if await DonorChannel.exists(channel_id=donor_id, recipient_channel=recipient):
        flash("Канал-донор уже прикреплен к этому каналу-получателю", "error")
        return redirect(url_for("recipient.recipient_add_donor", id=id))

    donor_name = (await client.get_chat(donor_id)).title

    donor = await DonorChannel.create(channel_id=donor_id, name=donor_name, recipient_channel=recipient)

    flash("Канал-донор успешно добавлен", "success")
    return redirect(url_for("recipient.recipient_page", id=id))


@bp.route("/recipient/<int:id>/toggle", methods=["POST"])
@login_required
async def toggle_recipient(id: int):
    recipient = await RecipientChannel.get_or_none(id=id)
    if not recipient:
        flash("Канал не найден", "error")
        return redirect(url_for("index"))

    recipient.is_active = not recipient.is_active
    await recipient.save()

    flash(
        "Пересылка востановлена" if recipient.is_active else "Пересылка отключена",
        "success" if recipient.is_active else "warning",
    )

    return redirect(url_for("index"))


@bp.route("/recipient/<int:id>/fill", methods=["POST"])
@login_required
async def fill_recipient(id: int):
    try:
        limit = int(request.form.get("limit"))
    except ValueError:
        flash("Неверный формат числа", "error")
        return redirect(url_for("recipient.recipient_page", id=id))

    recipient = await RecipientChannel.get_or_none(id=id)
    if not recipient:
        flash("Канал не найден", "error")
        return redirect(url_for("index"))

    await recipient.fetch_related("donor_channels")
    donor = recipient.donor_channels[0]
    if not donor:
        flash("Канал-донор не найден", "error")
        return redirect(url_for("recipient.recipient_page", id=id))

    await fill_channel(client, donor, recipient, limit)

    flash("Канал-получатель успешно заполнен", "success")
    return redirect(url_for("recipient.recipient_page", id=id))

web/templates/add_donor.html
{% extends "base.html" %}

{% block content %}
<h2>Добавление дополнительного канала-донора для {{ recipient.name }}</h2>
<form action="" method="POST" class="add-form">
    <label for="donor">Откуда брать:</label>
    <select name="donor" required>
        <option value="">-- выберите канал-донор --</option>
        {% for channel in possible_donor_channels %}
        <option value="{{ channel.id }}">{{ channel.title }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Добавить">
</form>
{% endblock %}

web/templates/add_filter.html
{% extends "base.html" %}

{% block styles %}
{{ super() }}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock styles %}

{% block content %}
<h2>Добавление фильтра</h2>

<form method="post" action="" class="add-form">
    <input required type="text" name="name" placeholder="Название фильтра">
    <label for="action">Действие:</label>
    <select name="action" required>
        <option value="">-- выбрать -- </option>
        <option value="SKIP">Пропустить это сообщение</option>
        <option value="PAUSE">Приостановить пересылку</option>
        <option value="REPLACE">Заменить</option>
    </select>
    <label for="scope">Область влияния:</label>
    <select name="scope" required>
        <option value="">-- выбрать -- </option>
        <option value="GLOBAL">Везде</option>
        <option value="RECIPIENT">Везде для канала-получателя</option>
        <option value="DONOR">Для всего из канала-донора</option>
    </select>
    <label for="recipient_id">Канал-получатель:</label>
    <select name="recipient_id">
        <option value="">-- выбрать -- </option>
        {% for recipient in recipients %}
        <option value="{{ recipient.id }}">{{ recipient.name }}</option>
        {% endfor %}
    </select>
    <label for="donor_id">Канал-донор:</label>
    <select name="donor_id">
        <option value="">-- выбрать -- </option>
        {% for donor in donors %}
        <option value="{{ donor.id }}">{{ donor.name  }} (для '{{ donor.recipient_channel.name }}')</option>
        {% endfor %}
    </select>

    <label for="pattern">Что искать:</label>
    <div>
        <label for="is_regex">Регулярное выражение (для сложных фильтров по почте и тд):</label>
        <input type="checkbox" name="is_regex">
    </div>
    <div>
        <label for="is_case_sensitive">Чувствительно к регистру (если активно - ищет точное совпадение):</label>
        <input type="checkbox" name="is_case_sensitive">
    </div>
    <input required type="text" name="pattern" placeholder="что искать">
    <label for="replace_with">На что заменять:</label>
    <input type="text" name="replace_with" placeholder="на что заменять">
    <input type="submit" value="Добавить">
</form>
{% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='js/add_filter.js') }}"></script>
{% endblock scripts %}

web/templates/add_recipient.html
{% extends "base.html" %}

{% block content %}
<h2>Добавление правила</h2>
<form action="" method="POST" class="add-form">
    <label for="name">Название правила:</label>
    <input type="text" name="name" placeholder="По умолчанию название канала">

    <label for="recipient">Куда постить:</label>
    <select name="recipient" required>
        <option value="">-- выберите канал --</option>
        {% for channel in admined_channels %}
        <option value="{{ channel.id }}">{{ channel.title }}</option>
        {% endfor %}
    </select>

    <label for="donor">Откуда брать:</label>
    <select name="donor" required>
        <option value="">-- выберите канал-донор --</option>
        {% for channel in possible_donor_channels %}
        <option value="{{ channel.id }}">{{ channel.title }}</option>
        {% endfor %}
    </select>
    <p>Позже можно будет добавить еще доноров</p>

    <label for="max_per_day">Максимум пересылок в день (0 - Неограниченно):</label>
    <input type="number" name="max_per_day"  min="0">

    <input type="submit" value="Добавить">
</form>
{% endblock %}

web/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    {% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">

    {% endblock %}

    <title>Telegram Republisher</title>
</head>

<body>
    <header>
        <a href="{{ url_for('index') }}">
            <img class="logo" src="{{ url_for('static', filename='img/logo.png') }}" alt="logo">
        </a>
        {% if session.get("logged_in") %}
        <a href="{{ url_for('logout') }}">Выйти</a>
        {% endif %}
    </header>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <ul class=flashes>
        {% for category, message in messages %}
        <li class="{{ category }}">
            <p>{{ message }}</p>
            <button class="close" onclick="this.parentElement.style.display='none';">&times;</button>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}

    <section class="main">
        {% block content %}
        {% endblock %}
    </section>

    {% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
    {% endblock %}
</body>

</html>

web/templates/donor.html
{% extends "base.html" %}

{% block content %}
{{ donor}}
<form action="{{ url_for('donor.delete_donor', id=donor.id) }}" method="POST">
    <input type="submit" value="Удалить">
</form>
{% endblock content %}

web/templates/index.html
{% extends "base.html" %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
{% endblock %}

{% block content %}
<div class="wrapper">
    <div class="recipients">
        <h2>Заполняемые каналы:</h2>
        {% if recipients %}
        <div class="cards recipient_cards">
            {% for recipient in recipients %}
            <div class="card recipient_card {% if not recipient.is_active %}disabled{% endif %}">
                <div class="title">
                    <a href="{{ url_for('recipient.recipient_page', id=recipient.id) }}">
                        [{{ recipient.id }}] {{ recipient.name }}
                    </a>
                    <p class="id">
                        tgid: {{ recipient.channel_id}}
                    </p>
                </div>
                <div class="donoros">
                    <p class="donor_title">Каналы-доноры:</p>
                    <ul class="donors_list">
                        {% for donor in recipient.donor_channels %}
                        <li class="donor {% if not donor.is_active %}disabled{% endif %}">
                            <a href="{{ url_for('donor.donor_page', id=donor.id) }}" class="donor_link">
                                <p class="donor_name">{{donor.name}}</p>
                            </a>
                            <p class="id">
                                tgid: {{donor.channel_id}}
                            </p>
                        </li>
                        {% endfor %}
                </div>
                {% if recipient.filters  %}
                <p>есть фильтры</p>
                {% endif %}
                <div class="action_forms">
                    <form action="{{ url_for('recipient.toggle_recipient', id=recipient.id) }}" class="delete_form" method="POST">
                        <input type="submit" value="{% if recipient.is_active %}Отключить{% else %}Включить{% endif %}">
                    </form>
                    <form action="{{ url_for('recipient.delete_recipient', id=recipient.id) }}" class="toggle_form" method="POST">
                        <input type="submit" value="Удалить">
                    </form>
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <p>Нет заполняемых каналов</p>
        {% endif %}
        <a class="add_link add_channel" href="{{url_for('recipient.add_recipient_page')}}">Добавить канал</a>
    </div>

    <div class="global_filters">
        <h2>Глобальные фильтры:</h2>
        {% if global_filters %}
        <div class="cards filter_cards">
            {% for filter in global_filters %}
            <div class="card filter_card {% if not filter.is_active %}disabled{% endif %}">
                <div class="title">
                    <a href="{{ url_for('filter.filter_page', id=filter.id) }}">
                        [{{ filter.id }}] {% if filter.name %}{{ filter.name }}{% else %}Без имени{% endif %}
                    </a>
                </div>

                <p class="filter_pattern">
                    Шаблон: {{ filter.pattern }}
                </p>

                <p class="filter_action">
                    Действие:
                    {% if filter.action == 'SKIP' %}
                    Пропустить сообщение
                    {% elif filter.action == 'PAUSE' %}
                    Приостановить все пересылки
                    {% elif filter.action == 'REPLACE' %}
                    Заменить паттерн на `{{ filter.replace_with }}`
                    {% endif %}
                </p>

                <div class="action_forms">
                    <form action="{{ url_for('filter.toggle_filter', id=filter.id) }}" class="delete_form" method="POST">
                        <input type="submit" value="{% if filter.is_active %}Отключить{% else %}Включить{% endif %}">
                    </form>
                    <form action="{{ url_for('filter.delete_filter', id=filter.id) }}" class="toggle_form" method="POST">
                        <input type="submit" value="Удалить">
                    </form>
                </div>

            </div>
            {% endfor %}
        </div>
        {% else %}
        <p>Нет глобальных фильтров</p>
        {% endif %}
        <a class="add_link add_filter" href="{{url_for('filter.add_filter_page')}}">Добавить фильтр</a>
    </div>
</div>
{% endblock %}

web/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
{% endblock %}


{% block content %}
<h2>Для работы необходимо авторизоваться</h2>
<form action="" method="post" class="login_form">
    <input type="password" name="password" placeholder="пароль">
    <input type="submit" value="Войти">
</form>
{% endblock %}

web/templates/recipient.html
{% extends "base.html" %}

{% block content %}
{{ recipient}}
<div class="action_forms">
    <form action="{{ url_for('recipient.toggle_recipient', id=recipient.id) }}" class="delete_form" method="POST">
        <input type="submit" value="{% if recipient.is_active %}Отключить{% else %}Включить{% endif %}">
    </form>
    <form action="{{ url_for('recipient.delete_recipient', id=recipient.id) }}" class="toggle_form" method="POST">
        <input type="submit" value="Удалить">
    </form>
</div>
<a href="{{ url_for('recipient.recipient_add_donor', id=recipient.id) }}">Добавить еще канал-донор</a>

<form action="{{ url_for('recipient.fill_recipient', id=recipient.id) }}" method="POST">
    <input type="number" value='100' name="limit" placeholder="Лимит сообщений">
    <input type="submit" value="Заполнить">
</form>


{% endblock content %}